config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  # get '/about', to: 'static_pages#about'
  get '/work', to: 'static_pages#work'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about; end
  def work; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bill Kohler</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_music_select.html.erb
<% if params[:music] %>
  <div class="space-breaker"></div>
  <ul>
    <li>
      <%= link_to "now playing 'flip out' by jai paul",
                  'https://soundcloud.com/apmitra/flip-out' %>
    </li>
  </ul>
  <%= render 'soundcloud_music_autoplay' %>
<% else %>
  <%= link_to 'play music', root_path(music: true) %>
<% end %>

app/views/shared/_soundcloud_music.html.erb
<iframe
  width="100%"
  height="166"
  scrolling="no"
  frameborder="no"
  allow="autoplay"
  src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/206728279&amp;color=%23c4948c&amp;auto_play=true&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true"></iframe>

app/views/shared/_soundcloud_music_autoplay.html.erb
<div class="hidden">
  <iframe
    width="100%"
    height="166"
    scrolling="no"
    frameborder="no"
    allow="autoplay"
    src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/206728279&amp;color=%23c4948c&amp;auto_play=true&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true"></iframe>
</div>

app/views/static_pages/_souncloud_music.html.erb
<div class="hidden">
  <iframe
    width="100%"
    height="166"
    scrolling="no"
    frameborder="no"
    allow="autoplay"
    src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/206728279&amp;color=%23c4948c&amp;auto_play=true&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true"></iframe>
</div>

app/views/static_pages/about.html.erb
<div class="home about face-banner %>">
  <div class="home-wrapper">
    <%= link_to (image_tag 'name-5'), 'mailto:bkohler4@gmail.com?' %>

    <div class="about-links">
      <ul>
        <li>  <%= link_to 'code', "https://github.com/williamkohler" %></li>
        <li><%= link_to 'film',
        "https://letterboxd.com/williamkohler/likes/films/by/release/" %></li>
        <li><%= link_to 'music',
        "https://www.last.fm/user/mifami" %>
        </li>
        <li><%= link_to 'Resume',
        "https://drive.google.com/open?id=14b-0VZQkaJFLOYYzuaskF--b5EBIx7QB" %></li>
      </ul>
      <div class="face-test"></div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="video-wrapper">
  <%= video_tag("dancing-1986-1987-2.mp4", autoplay: :autoplay,
                                           loop: :loop,
                                           muted: true,
                                           playsinline: true,
                                           controls: false,
                                           id: 'video-background') %>
  <div class="overlay-desc">
    <div>
      <%= link_to (image_tag 'name-7'), 'mailto:bkohler4@gmail.com?' %>
    </div>
    <div class="test-links">
      <ul>
        <li>
          <%= link_to "code i've written", "https://github.com/williamkohler" %>
        </li>
        <li><%= link_to "work i've done", work_path %>
        </li>
      </ul>
      <div class="space-breaker"></div>
      <ul>
        <li><%= link_to 'films i like',
        "https://letterboxd.com/williamkohler/likes/films/by/release/" %>
        </li>
        <li><%= link_to "music i'm listening to",
                        "https://www.last.fm/user/mifami" %>
        </li>
      </ul>
      <div class="space-breaker"></div>
      <ul>
        <li><%= link_to 'contact', 'mailto:bkohler4@gmail.com?' %></li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/test.html.erb
  <div class="video-wrapper">
    <%= video_tag('dancing-1986-1987.mp4', autoplay: :autoplay,
                                loop:     :loop,
                                muted:    :true,
                                id:       'video-background') %>
    <div class="overlay-desc">
      <div>
        <%= link_to (image_tag 'name-6'), 'mailto:bkohler4@gmail.com?' %>
      </div>
      <div class="test-links">
        <ul>
          <li>  <%= link_to 'code', "https://github.com/williamkohler" %></li>
          <li><%= link_to 'film',
          "https://letterboxd.com/williamkohler/likes/films/by/release/" %></li>
          <li><%= link_to 'music',
          "https://www.last.fm/user/mifami" %>
          </li>
          <li><%= link_to 'Resume',
          "https://drive.google.com/open?id=14b-0VZQkaJFLOYYzuaskF--b5EBIx7QB" %></li>
        </ul>
      </div>



    </div>

  </div>
  <div class="audio">
    <!-- does not work with safari -->
    <%= audio_tag('song-1.mp3', controls:     true,
                                    loop:     true,
                                    autoplay: true,
                                    hidden:   true )%>
  </div>

app/views/static_pages/work.html.erb
<div class="video-wrapper">
  <%= video_tag("dancing-1986-1987-1.mp4", autoplay: :autoplay, loop: :loop, muted: true, playsinline: true, controls: false, id: 'video-background') %>
  <div class="overlay-desc">
    <div>
      <%= link_to (image_tag 'name-7'), 'mailto:bkohler4@gmail.com?' %>
    </div>
    <div class="test-links">
      <ul>
        <li><%= link_to 'artist portal', 'https://artist-portal.herokuapp.com' %></li>
        <li><%= link_to 'hot dogs', 'https://hot-dogs-app.herokuapp.com' %></li>
        <li><%= link_to 'gradebook', 'https://gradebook-app.herokuapp.com' %></li>
      </ul>
      <div class="space-breaker"></div>
      <ul>
        <li><%= link_to 'resume', 'https://drive.google.com/open?id=14b-0VZQkaJFLOYYzuaskF--b5EBIx7QB' %></li>
      </ul>
    </div>
  </div>
</div>